version: "3"
services:
  frigate:
    container_name: frigate
    build:
      context: .
      dockerfile: docker/main/Dockerfile
      target: frigate
    restart: unless-stopped
    privileged: true
    shm_size: "256mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb # USB Coral
      # - /dev/dri:/dev/dri # Intel hwaccel, uncomment if you have Intel processor
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      - ./videos:/videos
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"  # Web UI
      - "5000:5000"  # Internal API
      - "8554:8554"  # RTSP restreaming
      - "8555:8555"  # WebRTC
      - "8556:8556"  # STUN server
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      YOLO_MODELS: "yolov4-tiny-416" # Default model, you can change this based on your needs

  mqtt:
    container_name: mqtt
    restart: unless-stopped
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/mosquitto/config